spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: avatar-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/avatardb
    username: user
    password: user
server:
  port: 8087
file:
  upload-dir: uploads