server:
  port: 8085
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true