spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: search-service-group
      properties:
        spring:
          json:
            value:
              default:
                type: imdb.searchservice.dto.MovieEvent
            trusted:
              packages: "*"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
server:
  port: 8084

app:
  kafka:
    topic:
      search-service:
        load-to-elastic: LOAD-ALL
        update: UPDATE
        create: CREATE
        delete: DELETE
  security:
    secret-key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
