spring:
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: user
    username: user
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/userdb
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true

app:
  urls:
    code: http://localhost:8086/verification-service/send-code
  kafka:
    producer:
      topic:
        verification: VERIFICATION
  security:
    secret: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9" # todo: вынести секреты в Vault
    expiration: "36000000"
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security=DEBUG: