spring:
  application:
    name: web-service
    jackson:
      deserialization:
        fail-on-unknown-properties: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
server:
  port: 8082
app:
  security:
    secret-key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  urls:
    search-service:
      search: http://localhost:8084/search-service/search
      all: http://localhost:8084/search-service/all
      test-all: http://localhost:8084/search-service/test-all
    delete: http://localhost:8081/auth/delete/{id}
    getAll: http://localhost:8081/auth/all
    user-service: http://localhost:8081/auth
    login: http://localhost:8081/auth/login
    register: http://localhost:8081/auth/register/user  #todo:вынести в Vault
    token: http://localhost:8081/auth/token
    registerAdmin: http://localhost:8081/auth/register/admin
    code: http://localhost:8086/verification-service/send-code
    codeFromCache: http://localhost:8086/verification-service/get-code